backend: 
  name: github
  repo: lyndsayfearnall/last-netlify-cms-tutorial


media_folder: static/img
public_folder: assets

collections: 
  - name: policy
    label: Policy Page
    folder: src/pages/policy
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Main Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - { name: title, label: Title }
          - { name: image, label: Image,  widget: image }
          - { name: heading, label: Heading, widget: string }
          - { name: subheading, label: Subheading, widget: string }
          - {label: Features, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/programs/index.md
        label: Programs
        name: programs
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/visit/index.md
        label: Visit
        name: visit
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/contact/index.md
        label: Contact
        name: contact
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/members/index.md
        label: Members
        name: members
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/massage/index.md
        label: Massage
        name: massage
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }