backend: 
  name: github
  repo: lyndsayfearnall/last-netlify-cms-tutorial


media_folder: static/img
public_folder: assets

collections: 
  - name: pages
    label: Main Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - { name: heading, label: Heading, widget: string }
          - { name: hero, label: Main Image, widget: object, fields: [{name: image, label: Image, widget: image}, {name: alt, label: Image Alt Text, widget: string, hint: Write a short description of the image (for accessibility purposes).}] }
          - { name: subheading, label: Subheading, widget: string }
          - { name: features, label: Features, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Image, name: image, widget: object, fields: [{name: image, label: Image, widget: image}, {name: alt, label: Image Alt Text, widget: string, hint: Write a short description of the image (for accessibility purposes).}] }, {label: Description, name: description, widget: markdown }], hint: This section is designed to have three features showcased on the home page.}
          - { name: links, label: Page Links, widget: list, hint: This section is designed to have two page links on the home page., fields: [{ name: title, label: Section Title, widget: string}, { name: subtitle, label: Subtitle, widget: string}, { name: button, label: Button Text, widget: string}, { name: url, label: Button URL, widget: string}, { name: image, label: Background Image, widget: object, fields: [{name: image, label: Image, widget: image}, {name: alt, label: Image Alt Text, widget: string, hint: Write a short description of the image (for accessibility purposes).}] }]}
          - { name: testimonials, label: Testimonials, widget: relation, collection: testimonial, searchFields: path, displayFields: [ name ], valueField: name, multiple: true, hint: Pick three testimonails to be featured on the home page. }
          - { name: nash, label: Nash Cup Section, widget: object, fields: [ {name: logo, label: Nash Cup Logo, widget: object, fields: [{name: image, label: Image, widget: image}, {name: alt, label: Alt Text, widget: string, hint: Write a short description of the image (for accessibility purposes).}]}, { name: subtitle, label: Main Text, widget: markdown }] }
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - { name: title, label: Page Title }
          - { name: image, label: Banner Image, widget: object, fields: [{name: image, label: Image, widget: image}, {name: alt, label: Image Alt Text, widget: string, hint: Write a short description of the image (for accessibility purposes).}] }
          - { name: heading, label: Heading }
          - { name: body, label: About Text, widget: markdown }
          - { name: featureImg, label: Feature Image, widget: object, fields: [{name: image, label: Image, widget: image}, {name: alt, label: Image Alt Text, widget: string, hint: Write a short description of the image (for accessibility purposes).}], hint: This image will be displayed to the right of your main text. }
          - { name: galleryImg, label: Gallery Images, widget: list, hint: The ideal number of images in this gallery is three., fields: [{name: image, label: Gallery Image, widget: object, fields: [{name: image, label: Image, widget: image}, {name: alt, label: Image Alt Text, widget: string, hint: Write a short description of the image (for accessibility purposes).}] }]}
          - { name: preFooter, label: Pre-Footer, widget: relation, collection: prefooter, searchFields: path, displayFields: [path], valueField: path, required: false, hint: The prefooter appears as a green bar at the bottom of this page. }
      - file: src/pages/programs/index.md
        label: Programs
        name: programs
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/visit/index.md
        label: Visit
        name: visit
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/contact/index.md
        label: Contact
        name: contact
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/members/index.md
        label: Members
        name: members
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
      - file: src/pages/massage/index.md
        label: Massage
        name: massage
        fields:
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
  - name: policy
    label: Policy Pages
    folder: src/pages/policy
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: testimonial
    label: Testimonials
    folder: src/pages/testimonials
    create: true
    fields:
      - { name: path, label: Name }
      - { label: Quote, name: quote, widget: markdown}
      - { label: Years as a Member, name: years, widget: number, valueType: int, hint: How many years has this person been a member? }
  
  - name: programs
    label: Programs
    folder: src/pages/program-options
    create: true
    fields:
      - { name: path, label: Program Name }
      - { label: Image, name: image, widget: image}
      - { label: Program Description, name: description, widget: markdown }

  - name: prefooter
    label: Pre-Footer Options
    folder: src/pages/prefooter
    create: true
    fields:
      - { name: path, label: Heading }
      - { label: Subtext, name: subtext, widget: text, required: false }
      - { label: Button Text, name: buttontext, widget: string }
      - { name: buttonUrl, label: Button URL, widget: string }